hash-format = "sha256"

[[files]]
file = "mods/advanced-networking.pw.toml"
hash = "50fcbe10eac3abf0b80b9a4bab9c43cee1890e796328e807c3daa5bf0b2f3e50"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6869de1ca55dc09beabb3c234727e84be4d4fbdcbad2c8081c03010713f374e1"
metafile = true

[[files]]
file = "mods/arch-ex.pw.toml"
hash = "0e08322161ff858b898c5b3c8888bc7ea1a6b1deea9cc68cb3b104e35db0357a"
metafile = true

[[files]]
file = "mods/aurorasdecorations.pw.toml"
hash = "b7d82cd112896a6e2c94b5c51bcbd21e7cba294c88f0e2f7b886eb382bad2353"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "cbf5544ba86d4d10262fff9c53af6c9ef05bb92d329bb02f891a5aaf3ca94631"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "7db433b63d957485d7cd5e36b649aae4d97a71ac49c657875b3a05f2c220d1c3"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "5081f2c48062e37a7b7a8bee8d0645b1cfb8876ddac6cbd8284beebd4427bb57"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b6348f94ec939f563285dc96683e61da8fc17ab2f2897be2751fa24789513691"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "e5bbc96d6d5d6bffb8e36c89bbd1331d923e23fbb87be8bae208d206832adb1c"
metafile = true

[[files]]
file = "mods/create-origins.pw.toml"
hash = "19cc41539f86ebe295ad79eed260104665b0427ec329e9faf46e42c0744d6f96"
metafile = true

[[files]]
file = "mods/create-snr.pw.toml"
hash = "b7e380163fd9212bc622e10501b1a502c233012a7b071400b848913e90cfc333"
metafile = true

[[files]]
file = "mods/create-utilities.pw.toml"
hash = "300fb5ae69227b226be00750dc5d5734d26592a54cc104295d30f89bcbb05527"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "e6cd8a58a2938b799035c66df16b440db0edf09c798978b8e857a6a27e8a6474"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
hash = "8766521465c1cc6b57199a24008be030eabfd417c0ba7eb6c91f26c2f6ffa70a"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "4f0afa4e70e830f08266c181c2a0deb207780712db6e7f8961ffb62061afada0"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
hash = "4c59088a2cb975f60347da57d72bb1069b65452c6a7b92af8facec6e1bed9409"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
hash = "cdb7cd286ed6706a6481a3a07c5017635d322c175351720503f6d59ee38d4020"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
hash = "76a2166b6bc2678069a93ced5969d56ee8189d6a30a86f57da75bd89af0e7f4c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "85daf558c36022a664c9e2bc3d9a9bc21cb9fa62977890f142c20ccc155eae36"
metafile = true

[[files]]
file = "mods/industrial-revolution.pw.toml"
hash = "622e468100dd3c51985c6587ec0a9b73d7962f3ddd31c6e86f0ba6bc676c94f6"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "659e2447deffc797f441ed09c0b05d75138253dfacfe1479d3938e55773be4b6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/modern-industrialization.pw.toml"
hash = "3ee62cce8cb44ef7cccf89e40bdb279b195f252fd1a7fdfc03be4303f38486cd"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e2a93bfe1d1e55657afd64a361b1d05929c8984332f1c39afd957eb7f88e9a62"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "f4302fdd9966919ded8743b20368e270faa003d023326e62110f7ca6e1b979df"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "669008dbd2508a67f8c409096cf2357de450f26a69494289e5852045ade7d358"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "e09b4e3348ee5e8b836e40ea4745bf3ab0d584512e31166ab34a219c437a736a"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
hash = "822cb71ea6d0986f90f01d1df5eee941334073cddc7b9abbe0398ba76c31fdaf"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "b0615e667641dd52e900c970553e0ce80748645dfaa93117bb126dccae3e3c19"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "7ffa8a332d46b6b412904e52353d7095b4709de406699d75bc31dc99ce416487"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2cadde7b91d76a9376b6335b1215b734e8d75473c594a7b75ebb220ff7e2c017"
metafile = true

[[files]]
file = "mods/simple-pipes.pw.toml"
hash = "982469e3629a7fc474a2b8c555b96879e8f5ea8a43d69b61c35b0d5e045ee11d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "28886fd5471a7a5cc215f155991e1628aaa86224da1cf46e1c2d12cef88118f4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "217b07516517c4c01958387192143943f3e9309a0e935828f9f32af771425d66"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "6fdaaa96fba5b4c71daecf7249b90c1aad2b9a27f92355826245177820804af5"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
hash = "e08ed79fafeb21ca809e76f4b328ecff1d30f2cfae62687087310eafd74b9cbd"
metafile = true

[[files]]
file = "mods/toomanyorigins.pw.toml"
hash = "e325de1cac72215e0cb28eab24f16fc55df4762b930d133818f5f653135b9b75"
metafile = true

[[files]]
file = "mods/wiredredstone.pw.toml"
hash = "1f86bbf321f45c7068c8cbfbbac276ddc31637c29344af3cbd139ef6d0c1bb26"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "fc11ca1eec1dc3785b51c51b061fed1a68044cd7ffb412cdabdaf76ecc0d9a29"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "0e6c95ef1ccab7d1c56a0222ecc3072e1ac9dfae171ae860e3d0e9a1a008e529"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "6c1a9c599f7c81d6c2f39533b335afe410a3beeb6d2b02b251ad74d5c7a34782"
metafile = true

[[files]]
file = "mods/yttr.pw.toml"
hash = "4f81b024490b0a27b868dfda67130b082e524c79d232d6c3dae39f6f2b8e11f1"
metafile = true
