hash-format = "sha256"

[[files]]
file = "mods/arch-ex.pw.toml"
hash = "0e08322161ff858b898c5b3c8888bc7ea1a6b1deea9cc68cb3b104e35db0357a"
metafile = true

[[files]]
file = "mods/aurorasdecorations.pw.toml"
hash = "b7d82cd112896a6e2c94b5c51bcbd21e7cba294c88f0e2f7b886eb382bad2353"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "e5bbc96d6d5d6bffb8e36c89bbd1331d923e23fbb87be8bae208d206832adb1c"
metafile = true

[[files]]
file = "mods/create-snr.pw.toml"
hash = "b7e380163fd9212bc622e10501b1a502c233012a7b071400b848913e90cfc333"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
hash = "e6cd8a58a2938b799035c66df16b440db0edf09c798978b8e857a6a27e8a6474"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "4f0afa4e70e830f08266c181c2a0deb207780712db6e7f8961ffb62061afada0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "03e174cf691b52da20bd973b955fae6f3720d3d2120f9d6cc1de5fdf3180013c"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "85daf558c36022a664c9e2bc3d9a9bc21cb9fa62977890f142c20ccc155eae36"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "659e2447deffc797f441ed09c0b05d75138253dfacfe1479d3938e55773be4b6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c239c951796882b9c93e649a0dba4f2d95804441faaed707b686381b7a5c67da"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e2a93bfe1d1e55657afd64a361b1d05929c8984332f1c39afd957eb7f88e9a62"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "e09b4e3348ee5e8b836e40ea4745bf3ab0d584512e31166ab34a219c437a736a"
metafile = true

[[files]]
file = "mods/promenade.pw.toml"
hash = "822cb71ea6d0986f90f01d1df5eee941334073cddc7b9abbe0398ba76c31fdaf"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "b0615e667641dd52e900c970553e0ce80748645dfaa93117bb126dccae3e3c19"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "7ffa8a332d46b6b412904e52353d7095b4709de406699d75bc31dc99ce416487"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "2cadde7b91d76a9376b6335b1215b734e8d75473c594a7b75ebb220ff7e2c017"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "28886fd5471a7a5cc215f155991e1628aaa86224da1cf46e1c2d12cef88118f4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "217b07516517c4c01958387192143943f3e9309a0e935828f9f32af771425d66"
metafile = true

[[files]]
file = "mods/toomanyorigins.pw.toml"
hash = "e325de1cac72215e0cb28eab24f16fc55df4762b930d133818f5f653135b9b75"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "0e6c95ef1ccab7d1c56a0222ecc3072e1ac9dfae171ae860e3d0e9a1a008e529"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "6c1a9c599f7c81d6c2f39533b335afe410a3beeb6d2b02b251ad74d5c7a34782"
metafile = true
